
# default: &default
#   adapter: mysql2
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

development:
  adapter: mysql2
  encoding: utf8mb4
  database: developmentdb
  username: root
  password: Monisha@123
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8mb4
  database: testdb
  username: root
  password: Monisha@123
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8mb4
  database: railsdb
  username: root
  password: Monisha@123
  host: localhost
  port: 3306